In [1]:
from importlib import reload

In [76]:
import eda_scripts
data = eda_scripts.get_data('./data/orders.csv')

In [78]:
reload(eda_scripts)
data_new = eda_scripts.get_features(data)
data_new.head(20)

,delivery_area_id,date,orders_cnt,year,date_date,quarter,month,season,week,dow,doy,hour,hour_cos,hour_sin,bank_holidays,days_before_of_holiday,days_before_celebrations,days_after_of_holiday,days_after_celebrations
0,0,2021-04-01 10:00:00,9,2021,2021-04-01,2,4,2,13,3,91,10,-8.660254e-01,5.000000e-01,0,30,153,-24,-24
1,0,2021-04-01 11:00:00,1,2021,2021-04-01,2,4,2,13,3,91,11,-9.659258e-01,2.588190e-01,0,30,153,-24,-24
2,0,2021-04-01 13:00:00,1,2021,2021-04-01,2,4,2,13,3,91,13,-9.659258e-01,-2.588190e-01,0,30,153,-24,-24
3,0,2021-04-01 14:00:00,1,2021,2021-04-01,2,4,2,13,3,91,14,-8.660254e-01,-5.000000e-01,0,30,153,-24,-24
4,0,2021-04-01 15:00:00,2,2021,2021-04-01,2,4,2,13,3,91,15,-7.071068e-01,-7.071068e-01,0,30,153,-24,-24
5,0,2021-04-01 16:00:00,2,2021,2021-04-01,2,4,2,13,3,91,16,-5.000000e-01,-8.660254e-01,0,30,153,-24,-24
6,0,2021-04-01 18:00:00,3,2021,2021-04-01,2,4,2,13,3,91,18,-1.836970e-16,-1.000000e+00,0,30,153,-24,-24
7,0,2021-04-01 19:00:00,2,2021,2021-04-01,2,4,2,13,3,91,19,2.588190e-01,-9.659258e-01,0,30,153,-24,-24
8,0,2021-04-01 20:00:00,2,2021,2021-04-01,2,4,2,13,3,91,20,5.000000e-01,-8.660254e-01,0,30,153,-24,-24
9,0,2021-04-01 21:00:00,1,2021,2021-04-01,2,4,2,13,3,91,21,7.071068e-01,-7.071068e-01,0,30,153,-24,-24
10,0,2021-04-02 10:00:00,3,2021,2021-04-02,2,4,2,13,4,92,10,-8.660254e-01,5.000000e-01,0,29,152,-25,-25
11,0,2021-04-02 11:00:00,1,2021,2021-04-02,2,4,2,13,4,92,11,-9.659258e-01,2.588190e-01,0,29,152,-25,-25
12,0,2021-04-02 12:00:00,1,2021,2021-04-02,2,4,2,13,4,92,12,-1.000000e+00,1.224647e-16,0,29,152,-25,-25
13,0,2021-04-02 13:00:00,4,2021,2021-04-02,2,4,2,13,4,92,13,-9.659258e-01,-2.588190e-01,0,29,152,-25,-25
14,0,2021-04-02 14:00:00,3,2021,2021-04-02,2,4,2,13,4,92,14,-8.660254e-01,-5.000000e-01,0,29,152,-25,-25
15,0,2021-04-02 15:00:00,1,2021,2021-04-02,2,4,2,13,4,92,15,-7.071068e-01,-7.071068e-01,0,29,152,-25,-25
16,0,2021-04-02 17:00:00,1,2021,2021-04-02,2,4,2,13,4,92,17,-2.588190e-01,-9.659258e-01,0,29,152,-25,-25
17,0,2021-04-02 18:00:00,2,2021,2021-04-02,2,4,2,13,4,92,18,-1.836970e-16,-1.000000e+00,0,29,152,-25,-25
18,0,2021-04-02 19:00:00,3,2021,2021-04-02,2,4,2,13,4,92,19,2.588190e-01,-9.659258e-01,0,29,152,-25,-25
19,0,2021-04-02 20:00:00,2,2021,2021-04-02,2,4,2,13,4,92,20,5.000000e-01,-8.660254e-01,0,29,152,-25,-25

In [74]:
data_new[data_new['date_date'] == '2021-05-01']

,delivery_area_id,date,orders_cnt,year,date_date,quarter,month,season,week,dow,hour,hour_cos,hour_sin,bank_holidays,days_before_of_holiday_x,doy,days_before_of_holiday_y
325,0,2021-05-01 10:00:00,2,2021,2021-05-01,2,5,2,17,5,10,-8.660254e-01,0.500000,1,121,121,0
326,0,2021-05-01 16:00:00,1,2021,2021-05-01,2,5,2,17,5,16,-5.000000e-01,-0.866025,1,121,121,0
327,0,2021-05-01 17:00:00,1,2021,2021-05-01,2,5,2,17,5,17,-2.588190e-01,-0.965926,1,121,121,0
328,0,2021-05-01 18:00:00,5,2021,2021-05-01,2,5,2,17,5,18,-1.836970e-16,-1.000000,1,121,121,0
329,0,2021-05-01 19:00:00,2,2021,2021-05-01,2,5,2,17,5,19,2.588190e-01,-0.965926,1,121,121,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
823309,539,2021-05-01 19:00:00,1,2021,2021-05-01,2,5,2,17,5,19,2.588190e-01,-0.965926,1,121,121,0
848146,566,2021-05-01 16:00:00,1,2021,2021-05-01,2,5,2,17,5,16,-5.000000e-01,-0.866025,1,121,121,0
848147,566,2021-05-01 17:00:00,2,2021,2021-05-01,2,5,2,17,5,17,-2.588190e-01,-0.965926,1,121,121,0
848148,566,2021-05-01 18:00:00,2,2021,2021-05-01,2,5,2,17,5,18,-1.836970e-16,-1.000000,1,121,121,0
882852,592,2021-05-01 10:00:00,1,2021,2021-05-01,2,5,2,17,5,10,-8.660254e-01,0.500000,1,121,121,0